spring:
  config:
    import: application-secret.yml
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE.ENDPOINT_URL.dev}:5432/postgres
    username: ${DATABASE.USERNAME.dev}
    password: ${DATABASE.PASSWORD.dev}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

  threads:
    virtual:
      enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

claude:
  ai:
    api-key: ${CLAUDE.API-KEY.dev}
discord:
  error-alert-url: ${DISCORD.ERROR_ALERT_URL.dev}