package com.official.memento.member.domain.enums;

public enum JobType {
    TECHNOLOGY,
    DATA_ANALYTICS,
    DESIGN_CREATIVITY,
    BUSINESS_MANAGEMENT,
    EDUCATION_TRAINING,
    HEALTHCARE_WELLNESS,
    FREELANCE_SELF_EMPLOYMENT,
    SERVICE_HOSPITALITY,
    ENGINEERING_MANUFACTURING,
    OTHER
}
